config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :blog_posts do
    resource :cover_image, only: [:destroy], module: :blog_posts
  end

  root 'blog_posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_one_attached :cover_image
  has_rich_text :content

  validates :title, presence: true
  validates :content, presence: true

  scope :sorted, -> { order(arel_table[:published_at].desc.nulls_first).order(updated_at: :desc) }
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where('published_at <= ?', Time.current) }
  scope :scheduled, -> { where('published_at > ?', Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/blog_posts/cover_images_controller.rb
class BlogPosts::CoverImagesController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :authenticate_user!
  before_action :set_blog_post

  def destroy
    @blog_post.cover_image.purge_later

    respond_to do |format|
      format.html { redirect_to edit_blog_post_path(@blog_post) }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(@blog_post, :cover_image)) }
    end
  end

  private

  def set_blog_post
    @blog_post = BlogPost.find(params[:blog_post_id])
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog_post, except: [:index, :new, :create]

  def index
    @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
    @pagy, @blog_posts = pagy(@blog_posts)
  rescue Pagy::OverflowError
    redirect_to root_path(pagy: 1)
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
      flash[:notice] = 'post created successfully'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
      flash[:notice] = 'post successfully update'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
    flash[:notice] = 'successfully deleted post'
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :cover_image, :published_at)
  end

  def set_blog_post
    @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def authenticate_user!
    redirect_to new_user_session_path, alert: 'You must sign in or sign up to continue.' unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<div class="text-center">
  <%= form_with model: blog_post do |form| %>
    <% if form.object.errors.any? %>
      <div>
        <% form.object.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      </div>
    <% end %>

    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title, class: 'text-center'%>
    </div>

    <div class='p-3'>
      <%= form.label :cover_image %>
      <% if blog_post.cover_image.present? %>
      <div id='<%= dom_id(blog_post, :cover_image) %>'>
        <%= image_tag blog_post.cover_image, class: 'h-40 w-full rounded'%>
        <%= link_to 'remove cover image', blog_post_cover_image_path(blog_post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'no-underline rounded-full bg-red-100 px-2 text-black' %>
      </div>
      <% else %>
        <%= form.file_field :cover_image %>
      <% end %>
    </div>

    <div class='p-3'>
      <%= form.label :content %><br>
      <%= form.rich_text_area :content %>
    </div>

    <div class='p-3'>
      <%= form.label :published_at %><br>
      <%= form.datetime_select :published_at, include_blank: true%>
    </div>

      <%= form.button class: 'rounded-full bg-red-100 px-2 text-black' %>

  <% end %>
</div>

app/views/blog_posts/edit.html.erb
<div class="text-center">
  <h1>Edit Blog Post</h1>
</div>

<%= render partial: 'form', locals: {blog_post: @blog_post} %>

<div class='fixed top-0 left-100 right-10'>
  <%= link_to 'back', @blog_post, class: "rounded-full bg-red-200 px-2 no-underline" %>
</div>
<div class='text-center p-2'>
  <%= button_to 'Delete', @blog_post, method: :delete, data: {turbo_confirm: 'Are you sure'}, class: 'rounded-full bg-red-100 px-2 text-black' %>
</div>

app/views/blog_posts/index.html.erb
<% if user_signed_in? %>
  <div class='fixed top-0 left-100 right-10'>
     <button class="rounded-full ..."><%= link_to 'New blog', new_blog_post_path, class: "rounded-full bg-red-200 px-2 no-underline" %></button>
  </div>
<% end %>

<div class="text-center">
  <h1>My blog</h1>

  <% @blog_posts.each do |blog_post|%>
    <div class='bg-red-100' >
      <%= image_tag blog_post.cover_image, class: 'h-40 w-full rounded' if blog_post.cover_image.present? %>
      <h2><%= link_to blog_post.title, blog_post, class: 'no-underline' %></h2>
    </div>
    <% if user_signed_in? %>
      <% if blog_post.draft? %>
        <div class="p-2 rounded bg-gray-100 text-gray-900">draft</div>
      <% elsif blog_post.scheduled? %>
        <div class="p-2 rounded bg-blue-100 text-blue-900">scheduled</div>
      <% else %>
        <div class="p-2 rounded bg-green-100 text-green-900">published</div>
      <% end %>
    <% end %>
  <% end %>
  <div class="my-16">
    <% if @pagy.count > @pagy.items %>
      <%== pagy_nav(@pagy)%>
    <% end %>
  </div>

</div>

app/views/blog_posts/new.html.erb
<div class="text-center">
  <h1>New Blog Post</h1>
</div>

  <%= render partial: 'form', locals: {blog_post: @blog_post} %>

<div class='fixed top-0 left-100 right-10'>
  <% if user_signed_in? %>
    <%= link_to 'back', root_path, class: "rounded-full bg-red-200 px-2 no-underline" %>
  <% end %>
</div>

app/views/blog_posts/show.html.erb
<div class="text-center">
  <%= image_tag @blog_post.cover_image, class: 'h-40 w-full rounded' if @blog_post.cover_image.present? %>
  <h1><%= @blog_post.title %></h1>
  <p class='text-xl'><%= @blog_post.content %></p>
</div>

<div class='fixed top-0 left-100 right-10'>
  <% if user_signed_in? %>
    <%= link_to 'Edit', edit_blog_post_path(@blog_post), class: "rounded-full bg-red-200 px-2 no-underline " %>
  <% end %>
    <%= link_to 'back', root_path, class: "rounded-full bg-red-200 px-2 no-underline" %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='prose mx-auto'>
  <div class="text-center">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
  <br>
  <div class="fixed top-0 left-10 right-10">
    <% if user_signed_in? %>
      <%= button_to 'Log-out', destroy_user_session_path, method: :delete, class: "rounded-full bg-red-200 px-2 text-black " %>
    <% end %>
  </div>

    <%= yield %>
  </body>
</html>